services:
  - type: web
    name: fastapi-chat-ws
    env: python
    plan: free
    region: oregon        # choose your preferred region in Render

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.11

    healthCheckPath: /
